name = "ErrorfreeArithmetic"
uuid = "90fa49ef-747e-5e6f-a989-263ba693cf1a"
keywords = ["floating-point", "error-free", "extended-precision"]
repo = "https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl.git"
authors = ["Jeffrey A. Sarnoff <jeffrey.sarnoff@gmail.com>"]
license = "MIT"
version = "v0.5.3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Combinatorics", "Test"]

[compat]
julia = "1.7"
