desc = "Error-free arithmetic transformations."
keywords = ["floating-point", "error-free", "extended-precision"]
name = "ErrorfreeArithmetic"
uuid = "90fa49ef-747e-5e6f-a989-263ba693cf1a"
repo = "https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl.git"
author = "Jeffrey Sarnoff"
license = "MIT"
version = "v0.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
